version: '3'

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./docker/log:/var/log/container
      - ./docker/data:/etc/data
      - ./app:/app
    links:
      - postgres
    restart: on-failure


  postgres:
    env_file:
      - .env
    image: postgres:latest
    volumes:
      - ~/.ssh:/root/.ssh
      - ./docker/log:/var/log/container
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    restart: on-failure

#  redis:
#    env_file:
#      - .env
#    image: redis:alpine
#    ports:
#      - "6379:6379"
#    restart: on-failure

