version: '3'

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./docker/log:/var/log/container
      - ./docker/data:/etc/data
      - ./app:/app
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    env_file:
      - .env
    image: postgres:latest
    volumes:
      - ~/.ssh:/root/.ssh
      - ./docker/log:/var/log/container
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    restart: on-failure

#  rabbitmq:
#    env_file:
#      - .env
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    restart: on-failure

