jobs:
  - name: wbscrapy_new
    command: cd /app/wbscrapy && /usr/local/bin/project crawl products -a type=new
    schedule: "*/30 * * * *"

  - name: regular_scrapping
    command: cd /app/wbscrapy && python regular_scrapping
    schedule: "0 */2 * * *"

  - name: update_proxies
    command: cd /app/wbscrapy && python check_proxies.py
    schedule: "0 */12 * * *"
